# BOOK RECOMMENDER SYSTEM

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
books = pd.read_csv('books_1.Best_Books_Ever.csv',sep=";", on_bad_lines="skip", encoding='latin-1')

In [3]:
books = pd.read_csv("books_1.Best_Books_Ever.csv", delimiter=',')

In [4]:
books.columns

Index(['bookId', 'title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')

In [5]:
books.head(4)

,bookId,title,series,author,rating,description,language,isbn,genres,characters,...,firstPublishDate,awards,numRatings,ratingsByStars,likedPercent,setting,coverImg,bbeScore,bbeVotes,price
0,2767052-the-hunger-games,The Hunger Games,The Hunger Games #1,Suzanne Collins,4.33,WINNING MEANS FAME AND FORTUNE.LOSING MEANS CE...,English,9780439023481,"['Young Adult', 'Fiction', 'Dystopia', 'Fantas...","['Katniss Everdeen', 'Peeta Mellark', 'Cato (H...",...,NaN,['Locus Award Nominee for Best Young Adult Boo...,6376780,"['3444695', '1921313', '745221', '171994', '93...",96.0,"['District 12, Panem', 'Capitol, Panem', 'Pane...",https://i.gr-assets.com/images/S/compressed.ph...,2993816,30516,5.09
1,2.Harry_Potter_and_the_Order_of_the_Phoenix,Harry Potter and the Order of the Phoenix,Harry Potter #5,"J.K. Rowling, Mary GrandPré (Illustrator)",4.50,There is a door at the end of a silent corrido...,English,9780439358071,"['Fantasy', 'Young Adult', 'Fiction', 'Magic',...","['Sirius Black', 'Draco Malfoy', 'Ron Weasley'...",...,06/21/03,['Bram Stoker Award for Works for Young Reader...,2507623,"['1593642', '637516', '222366', '39573', '14526']",98.0,['Hogwarts School of Witchcraft and Wizardry (...,https://i.gr-assets.com/images/S/compressed.ph...,2632233,26923,7.38
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,07/11/60,"['Pulitzer Prize for Fiction (1961)', 'Audie A...",4501075,"['2363896', '1333153', '573280', '149952', '80...",95.0,"['Maycomb, Alabama (United States)']",https://i.gr-assets.com/images/S/compressed.ph...,2269402,23328,NaN
3,1885.Pride_and_Prejudice,Pride and Prejudice,NaN,"Jane Austen, Anna Quindlen (Introduction)",4.26,Alternate cover edition of ISBN 9780679783268S...,English,9999999999999,"['Classics', 'Fiction', 'Romance', 'Historical...","['Mr. Bennet', 'Mrs. Bennet', 'Jane Bennet', '...",...,01/28/13,[],2998241,"['1617567', '816659', '373311', '113934', '767...",94.0,"['United Kingdom', 'Derbyshire, England (Unite...",https://i.gr-assets.com/images/S/compressed.ph...,1983116,20452,NaN

In [6]:
books1= pd.read_csv('BX-Books.csv',sep=";",on_bad_lines ="skip", encoding='latin-1' )

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_8800\1637899438.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books1= pd.read_csv('BX-Books.csv',sep=";",on_bad_lines ="skip", encoding='latin-1' )

In [7]:
books1.head(2)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...

In [8]:
books1.columns

Index(['ISBN', 'Book-Title', 'Book-Author', 'Year-Of-Publication', 'Publisher',
       'Image-URL-S', 'Image-URL-M', 'Image-URL-L'],
      dtype='object')

In [9]:
books1.rename(columns={
    "ISBN": "isbn",
    "Book-Title":"title",
    "Book-Author": "author",
    "Year-Of-Publication":"year",
    "Publisher": "publisher",
    "Image-URL-M": "img"},inplace =True)

In [10]:
books1.head(4)

,isbn,title,author,year,publisher,Image-URL-S,img,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,Clara Callan,Richard Bruce Wright,2001,HarperFlamingo Canada,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,Decision in Normandy,Carlo D'Este,1991,HarperPerennial,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,Flu: The Story of the Great Influenza Pandemic...,Gina Bari Kolata,1999,Farrar Straus Giroux,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...

In [11]:
users = pd.read_csv('BX-Users.csv',sep=";", on_bad_lines="skip", encoding='latin-1')

In [12]:
users.head(4)

   User-ID                         Location   Age
0        1               nyc, new york, usa   NaN
1        2        stockton, california, usa  18.0
2        3  moscow, yukon territory, russia   NaN
3        4        porto, v.n.gaia, portugal  17.0

In [13]:
ratings = pd.read_csv('BX-Book-Ratings.csv',sep=";", on_bad_lines="skip", encoding='latin-1')

In [14]:
ratings.head(4)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0
1   276726  0155061224            5
2   276727  0446520802            0
3   276729  052165615X            3

In [15]:
ratings.rename(columns={
    "User-ID": "userid",
    "ISBN": "isbn",
    "Book-Rating": "rating"
},inplace =True)

In [16]:
ratings.head(4)

   userid        isbn  rating
0  276725  034545104X       0
1  276726  0155061224       5
2  276727  0446520802       0
3  276729  052165615X       3

In [17]:
ratings["userid"].unique().shape

(105283,)

In [18]:
x= ratings["userid"].value_counts()>200

In [19]:
x[x].shape

(899,)

In [20]:
y=x[x].index

In [21]:
y

Index([ 11676, 198711, 153662,  98391,  35859, 212898, 278418,  76352, 110973,
       235105,
       ...
       260183,  73681,  44296, 155916,   9856, 274808,  28634,  59727, 268622,
       188951],
      dtype='int64', name='userid', length=899)

In [22]:
ratings= ratings[ratings["userid"].isin(y)]

In [23]:
ratings.head()

      userid        isbn  rating
1456  277427  002542730X      10
1457  277427  0026217457       0
1458  277427  003008685X       8
1459  277427  0030615321       0
1460  277427  0060002050       0

In [24]:
ratings.shape

(526356, 3)

In [25]:
books1.head(1)

,isbn,title,author,year,publisher,Image-URL-S,img,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...

In [26]:
ratings_with_books = ratings.merge(books1, on="isbn")

In [27]:
ratings_with_books.head(3)

,userid,isbn,rating,title,author,year,publisher,Image-URL-S,img,Image-URL-L
0,277427,002542730X,10,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
1,3363,002542730X,0,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...
2,11676,002542730X,6,Politically Correct Bedtime Stories: Modern Ta...,James Finn Garner,1994,John Wiley &amp; Sons Inc,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...,http://images.amazon.com/images/P/002542730X.0...

In [28]:

rating_books=books.merge(ratings_with_books, on="title")

In [29]:
print(books.columns)
print(ratings_with_books.columns)

Index(['bookId', 'title', 'series', 'author', 'rating', 'description',
       'language', 'isbn', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price'],
      dtype='object')
Index(['userid', 'isbn', 'rating', 'title', 'author', 'year', 'publisher',
       'Image-URL-S', 'img', 'Image-URL-L'],
      dtype='object')

In [30]:
rating_books.head(3)

,bookId,title,series,author_x,rating_x,description,language,isbn_x,genres,characters,...,price,userid,isbn_y,rating_y,author_y,year,publisher_y,Image-URL-S,img,Image-URL-L
0,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,278418,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
1,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,2766,0446310786,10,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,4017,0446310786,10,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...

In [31]:
rating_books.columns

Index(['bookId', 'title', 'series', 'author_x', 'rating_x', 'description',
       'language', 'isbn_x', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher_x', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price', 'userid', 'isbn_y', 'rating_y',
       'author_y', 'year', 'publisher_y', 'Image-URL-S', 'img', 'Image-URL-L'],
      dtype='object')

In [32]:
rating_books.shape

(127007, 34)

In [33]:
books = pd.read_csv('books_1.Best_Books_Ever.csv',sep=";", on_bad_lines="skip", encoding='latin-1')

In [34]:
books.columns

Index(['bookId,"title","series","author","rating","description","language","isbn","genres","characters","bookFormat","edition","pages","publisher","publishDate","firstPublishDate","awards","numRatings","ratingsByStars","likedPercent","setting","coverImg","bbeScore","bbeVotes","price"'], dtype='object')

# Collabrative filtering recommender system

In [35]:
book_pivot= rating_books.pivot_table(columns= "userid",index="title", values="rating_x")
# Load your CSV file into a DataFrame

In [36]:
book_pivot

userid,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
'Salem's Lot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...And Ladies of the Club,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"1,000 Places to See Before You Die",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10 Secrets for Success and Inner Peace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100 Selected Poems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zombie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zorba the Greek,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya's Story: An Afghan Woman's Struggle for Freedom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
god bless the gargoyles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
print(book_pivot)

userid                                              254     2276    2766    \
title
'Salem's Lot                                           NaN     NaN     NaN
...And Ladies of the Club                              NaN     NaN     NaN
1,000 Places to See Before You Die                     NaN     NaN     NaN
10 Secrets for Success and Inner Peace                 NaN     NaN     NaN
100 Selected Poems                                     NaN     NaN     NaN
...                                                    ...     ...     ...
Zombie                                                 NaN     NaN     NaN
Zorba the Greek                                        NaN     NaN     NaN
Zoya                                                   NaN     NaN     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN     NaN     NaN
god bless the gargoyles                                NaN     NaN     NaN

userid                                              2977    3363    3757    \
title
'Salem's Lot                                           NaN     NaN     NaN
...And Ladies of the Club                              NaN     NaN     NaN
1,000 Places to See Before You Die                     NaN     NaN     NaN
10 Secrets for Success and Inner Peace                 NaN     NaN     NaN
100 Selected Poems                                     NaN     NaN     NaN
...                                                    ...     ...     ...
Zombie                                                 NaN     NaN     NaN
Zorba the Greek                                        NaN     NaN     NaN
Zoya                                                   NaN     NaN     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN     NaN     NaN
god bless the gargoyles                                NaN     NaN     NaN

userid                                              4017    4385    6242    \
title
'Salem's Lot                                           NaN     NaN     NaN
...And Ladies of the Club                              NaN     NaN     NaN
1,000 Places to See Before You Die                     NaN     NaN     NaN
10 Secrets for Success and Inner Peace                 NaN     NaN     NaN
100 Selected Poems                                     NaN     NaN     NaN
...                                                    ...     ...     ...
Zombie                                                 NaN     NaN     NaN
Zorba the Greek                                        NaN     NaN     NaN
Zoya                                                   NaN     NaN     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN     NaN     NaN
god bless the gargoyles                                NaN     NaN     NaN

userid                                              6251    ...  274004  \
title                                                       ...
'Salem's Lot                                           NaN  ...     NaN
...And Ladies of the Club                              NaN  ...     NaN
1,000 Places to See Before You Die                     NaN  ...     NaN
10 Secrets for Success and Inner Peace                 NaN  ...     NaN
100 Selected Poems                                     NaN  ...     NaN
...                                                    ...  ...     ...
Zombie                                                 NaN  ...     NaN
Zorba the Greek                                        NaN  ...     NaN
Zoya                                                   NaN  ...     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN  ...     NaN
god bless the gargoyles                                NaN  ...     NaN

userid                                              274061  274301  274308  \
title
'Salem's Lot                                           NaN     NaN     NaN
...And Ladies of the Club                              NaN     NaN     NaN
1,000 Places to See Before You Die                     NaN     NaN     NaN
10 Secrets for Success and Inner Peace                 NaN     NaN     NaN
100 Selected Poems                                     NaN     NaN     NaN
...                                                    ...     ...     ...
Zombie                                                 NaN     NaN     NaN
Zorba the Greek                                        NaN     NaN     NaN
Zoya                                                   NaN     NaN     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN     NaN     NaN
god bless the gargoyles                                NaN     NaN     NaN

userid                                              274808  275970  277427  \
title
'Salem's Lot                                           NaN     NaN     NaN
...And Ladies of the Club                              NaN     NaN     NaN
1,000 Places to See Before You Die                     NaN     NaN     NaN
10 Secrets for Success and Inner Peace                 NaN     NaN     NaN
100 Selected Poems                                     NaN     NaN     NaN
...                                                    ...     ...     ...
Zombie                                                 NaN     NaN     NaN
Zorba the Greek                                        NaN     NaN     NaN
Zoya                                                   NaN     NaN     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN     NaN     NaN
god bless the gargoyles                                NaN     NaN     NaN

userid                                              277478  277639  278418
title
'Salem's Lot                                           NaN     NaN     NaN
...And Ladies of the Club                              NaN     NaN     NaN
1,000 Places to See Before You Die                     NaN     NaN     NaN
10 Secrets for Success and Inner Peace                 NaN     NaN     NaN
100 Selected Poems                                     NaN     NaN     NaN
...                                                    ...     ...     ...
Zombie                                                 NaN     NaN     NaN
Zorba the Greek                                        NaN     NaN     NaN
Zoya                                                   NaN     NaN     NaN
Zoya's Story: An Afghan Woman's Struggle for Fr...     NaN     NaN     NaN
god bless the gargoyles                                NaN     NaN     NaN

[8303 rows x 898 columns]

In [38]:
rating_books.head(15)

,bookId,title,series,author_x,rating_x,description,language,isbn_x,genres,characters,...,price,userid,isbn_y,rating_y,author_y,year,publisher_y,Image-URL-S,img,Image-URL-L
0,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,278418,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
1,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,2766,0446310786,10,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
2,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,4017,0446310786,10,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
3,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,7346,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
4,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,11601,0446310786,10,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
5,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,11676,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
6,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,12538,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
7,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,13850,0446310786,9,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
8,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,16634,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
9,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,17950,0446310786,8,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
10,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,21014,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
11,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,21576,0446310786,8,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
12,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,23768,0446310786,0,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
13,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,23902,0446310786,7,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...
14,2657.To_Kill_a_Mockingbird,To Kill a Mockingbird,To Kill a Mockingbird,Harper Lee,4.28,The unforgettable novel of a childhood in a sl...,English,9999999999999,"['Classics', 'Fiction', 'Historical Fiction', ...","['Scout Finch', 'Atticus Finch', 'Jem Finch', ...",...,NaN,24194,0446310786,8,Harper Lee,1988,Little Brown &amp; Company,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...,http://images.amazon.com/images/P/0446310786.0...

In [39]:
rating_books.shape

(127007, 34)

In [40]:
unique_books = rating_books.drop_duplicates(subset='title')

In [41]:
unique_books.shape

(8303, 34)

In [42]:
unique_books.columns

Index(['bookId', 'title', 'series', 'author_x', 'rating_x', 'description',
       'language', 'isbn_x', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher_x', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price', 'userid', 'isbn_y', 'rating_y',
       'author_y', 'year', 'publisher_y', 'Image-URL-S', 'img', 'Image-URL-L'],
      dtype='object')

In [43]:
book_pivot

userid,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
'Salem's Lot,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...And Ladies of the Club,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
"1,000 Places to See Before You Die",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10 Secrets for Success and Inner Peace,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
100 Selected Poems,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zombie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zorba the Greek,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Zoya's Story: An Afghan Woman's Struggle for Freedom,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
god bless the gargoyles,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [44]:
book_pivot.fillna(0,inplace=True)

In [45]:
book_pivot

userid,254,2276,2766,2977,3363,3757,4017,4385,6242,6251,...,274004,274061,274301,274308,274808,275970,277427,277478,277639,278418
title,,,,,,,,,,,,,,,,,,,,,
'Salem's Lot,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...And Ladies of the Club,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
"1,000 Places to See Before You Die",0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10 Secrets for Success and Inner Peace,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
100 Selected Poems,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Zombie,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zorba the Greek,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
Zoya's Story: An Afghan Woman's Struggle for Freedom,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
god bless the gargoyles,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

## Traing Model

In [46]:
from scipy.sparse import csr_matrix

In [47]:
book_sparse = csr_matrix(book_pivot)

In [48]:
book_sparse

<8303x898 sparse matrix of type '<class 'numpy.float64'>'
	with 93813 stored elements in Compressed Sparse Row format>

In [49]:
from sklearn.neighbors import NearestNeighbors
model = NearestNeighbors(algorithm='brute')

In [50]:
model.fit(book_sparse)

NearestNeighbors(algorithm='brute')

In [51]:
distance, suggestion=  model.kneighbors(book_pivot.iloc[237,:].values.reshape(1,-1),n_neighbors=6)

In [52]:
distance

array([[0.  , 0.04, 0.12, 0.12, 0.13, 0.14]])

In [53]:
suggestion

array([[ 237,  953, 4326, 4787, 1429, 3086]], dtype=int64)

In [54]:
for i in range(len(suggestion)):
    print(book_pivot.index[suggestion[i]])

Index(['A Stillness at Appomattox', 'Boy in the Air', 'Power of Silence',
       'Selected Poetry', 'Dances with Wolves', 'King'],
      dtype='object', name='title')

In [55]:
book_pivot.index[3]

'10 Secrets for Success and Inner Peace'

In [56]:
book_pivot.columns[3]

2977

In [57]:
book_name= book_pivot.columns

# finding url

In [58]:
ids=np.where(rating_books['title']=="Twilight")[0][0]

In [59]:
rating_books.iloc[ids]['img']

'http://images.amazon.com/images/P/0671644076.01.MZZZZZZZ.jpg'

In [60]:
book_name=[]
for book_id in suggestion:
    book_name.append(book_pivot.index[book_id])

In [61]:
book_name[0]

Index(['A Stillness at Appomattox', 'Boy in the Air', 'Power of Silence',
       'Selected Poetry', 'Dances with Wolves', 'King'],
      dtype='object', name='title')

In [62]:
ids_index=[]
for name in book_name[0]:
    ids=np.where(rating_books['title']==name)[0][0]
    ids_index.append(ids)

In [63]:
for idx in ids_index:
    url = rating_books.iloc[idx]['img']
    print(url)

http://images.amazon.com/images/P/0844665509.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/1880985063.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/067173248X.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/0030091306.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/0517394499.01.MZZZZZZZ.jpg
http://images.amazon.com/images/P/0060161957.01.MZZZZZZZ.jpg

In [64]:
import pickle 
pickle.dump(model, open('model.pkl','wb'))
pickle.dump(book_name, open('book_name.pkl', 'wb'))
pickle.dump(rating_books, open('rating_books.pkl', 'wb'))
pickle.dump(book_pivot, open('book_pivot.pkl', 'wb'))

# testing model

In [65]:
def recommend_book(book_name):
    book_id= np.where(book_pivot.index== book_name)[0][0]
    distance, suggestion=  model.kneighbors(book_pivot.iloc[book_id,:].values.reshape(1,-1),n_neighbors=6)

    for i in range(len(suggestion)):
        books = book_pivot.index[suggestion[i]]
        for j in books:
            if j==book_name:
                print("You searched'{book_name}'\n")
                print("The suggestion books are: \n")
            else:
                print(j)

In [66]:
book_name = 'Harry Potter and the Prisoner of Azkaban'
recommend_book(book_name)

You searched'{book_name}'

The suggestion books are:

The Complete Works
Asterix and Cleopatra
Asterix in Switzerland
Collected Poems
The Kenneth Williams Diaries

# Content Based Recommender system (Author + Genre)

In [67]:
unique_books = unique_books[['title','author_x','description','genres','setting','img']]

In [68]:
unique_books.head()

,title,author_x,description,genres,setting,img
0,To Kill a Mockingbird,Harper Lee,The unforgettable novel of a childhood in a sl...,"['Classics', 'Fiction', 'Historical Fiction', ...","['Maycomb, Alabama (United States)']",http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)",Alternate cover edition of ISBN 9780679783268S...,"['Classics', 'Fiction', 'Romance', 'Historical...","['United Kingdom', 'Derbyshire, England (Unite...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,Stephenie Meyer,About three things I was absolutely positive.\...,"['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Forks, Washington (United States)', 'Phoenix...",http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"George Orwell, Russell Baker (Preface), C.M. W...",Librarian's note: There is an Alternate Cover ...,"['Classics', 'Fiction', 'Dystopia', 'Fantasy',...","['England', 'United Kingdom']",http://images.amazon.com/images/P/0451526341.0...
414,The Chronicles of Narnia,"C.S. Lewis, Pauline Baynes (Illustrator)","Journeys to the end of the world, fantastic cr...","['Fantasy', 'Classics', 'Fiction', 'Young Adul...","['London, England']",http://images.amazon.com/images/P/0590257889.0...

In [69]:
unique_books.isnull().sum()

title           0
author_x        0
description    62
genres          0
setting         0
img             0
dtype: int64

In [70]:
unique_books['description'] = unique_books['description'].astype(str)

In [71]:
unique_books['description'] = unique_books['description'].apply(lambda x:x.split())

In [72]:

unique_books.head()

,title,author_x,description,genres,setting,img
0,To Kill a Mockingbird,Harper Lee,"[The, unforgettable, novel, of, a, childhood, ...","['Classics', 'Fiction', 'Historical Fiction', ...","['Maycomb, Alabama (United States)']",http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"Jane Austen, Anna Quindlen (Introduction)","[Alternate, cover, edition, of, ISBN, 97806797...","['Classics', 'Fiction', 'Romance', 'Historical...","['United Kingdom', 'Derbyshire, England (Unite...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,Stephenie Meyer,"[About, three, things, I, was, absolutely, pos...","['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Forks, Washington (United States)', 'Phoenix...",http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"George Orwell, Russell Baker (Preface), C.M. W...","[Librarian's, note:, There, is, an, Alternate,...","['Classics', 'Fiction', 'Dystopia', 'Fantasy',...","['England', 'United Kingdom']",http://images.amazon.com/images/P/0451526341.0...
414,The Chronicles of Narnia,"C.S. Lewis, Pauline Baynes (Illustrator)","[Journeys, to, the, end, of, the, world,, fant...","['Fantasy', 'Classics', 'Fiction', 'Young Adul...","['London, England']",http://images.amazon.com/images/P/0590257889.0...

In [73]:
unique_books['author_x'] = unique_books['author_x'].apply(lambda x: [x])

In [74]:
unique_books.head()

,title,author_x,description,genres,setting,img
0,To Kill a Mockingbird,[Harper Lee],"[The, unforgettable, novel, of, a, childhood, ...","['Classics', 'Fiction', 'Historical Fiction', ...","['Maycomb, Alabama (United States)']",http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"[Jane Austen, Anna Quindlen (Introduction)]","[Alternate, cover, edition, of, ISBN, 97806797...","['Classics', 'Fiction', 'Romance', 'Historical...","['United Kingdom', 'Derbyshire, England (Unite...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,[Stephenie Meyer],"[About, three, things, I, was, absolutely, pos...","['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Forks, Washington (United States)', 'Phoenix...",http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"[George Orwell, Russell Baker (Preface), C.M. ...","[Librarian's, note:, There, is, an, Alternate,...","['Classics', 'Fiction', 'Dystopia', 'Fantasy',...","['England', 'United Kingdom']",http://images.amazon.com/images/P/0451526341.0...
414,The Chronicles of Narnia,"[C.S. Lewis, Pauline Baynes (Illustrator)]","[Journeys, to, the, end, of, the, world,, fant...","['Fantasy', 'Classics', 'Fiction', 'Young Adul...","['London, England']",http://images.amazon.com/images/P/0590257889.0...

In [79]:
def str_to_list(string):
    cleaned_string = string.strip("[]")
    return [item.strip() for item in cleaned_string.split(',')]
unique_books['genres'] = unique_books['genres'].apply(str_to_list)

In [80]:
unique_books['tags'] = unique_books['author_x'] + unique_books['description'] + unique_books['genres'] + unique_books['setting']

In [81]:
unique_books.head()

,title,author_x,description,genres,setting,img,tags
0,To Kill a Mockingbird,[Harper Lee],"[The, unforgettable, novel, of, a, childhood, ...","['Classics', 'Fiction', 'Historical Fiction', ...","['Maycomb, Alabama (United States)']",http://images.amazon.com/images/P/0446310786.0...,"[Harper Lee, The, unforgettable, novel, of, a,..."
186,Pride and Prejudice,"[Jane Austen, Anna Quindlen (Introduction)]","[Alternate, cover, edition, of, ISBN, 97806797...","['Classics', 'Fiction', 'Romance', 'Historical...","['United Kingdom', 'Derbyshire, England (Unite...",http://images.amazon.com/images/P/0451519167.0...,"[Jane Austen, Anna Quindlen (Introduction), Al..."
250,Twilight,[Stephenie Meyer],"[About, three, things, I, was, absolutely, pos...","['Young Adult', 'Fantasy', 'Romance', 'Vampire...","['Forks, Washington (United States)', 'Phoenix...",http://images.amazon.com/images/P/0671644076.0...,"[Stephenie Meyer, About, three, things, I, was..."
274,Animal Farm,"[George Orwell, Russell Baker (Preface), C.M. ...","[Librarian's, note:, There, is, an, Alternate,...","['Classics', 'Fiction', 'Dystopia', 'Fantasy',...","['England', 'United Kingdom']",http://images.amazon.com/images/P/0451526341.0...,"[George Orwell, Russell Baker (Preface), C.M. ..."
414,The Chronicles of Narnia,"[C.S. Lewis, Pauline Baynes (Illustrator)]","[Journeys, to, the, end, of, the, world,, fant...","['Fantasy', 'Classics', 'Fiction', 'Young Adul...","['London, England']",http://images.amazon.com/images/P/0590257889.0...,"[C.S. Lewis, Pauline Baynes (Illustrator), Jou..."

In [82]:
unique_books = unique_books[['title','tags','img']]
unique_books.head()

,title,tags,img
0,To Kill a Mockingbird,"[Harper Lee, The, unforgettable, novel, of, a,...",http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"[Jane Austen, Anna Quindlen (Introduction), Al...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,"[Stephenie Meyer, About, three, things, I, was...",http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"[George Orwell, Russell Baker (Preface), C.M. ...",http://images.amazon.com/images/P/0451526341.0...
414,The Chronicles of Narnia,"[C.S. Lewis, Pauline Baynes (Illustrator), Jou...",http://images.amazon.com/images/P/0590257889.0...

In [83]:
unique_books['tags'] = unique_books['tags'].apply(lambda x:" ".join(x))

In [84]:
import nltk

In [85]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [86]:
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

In [87]:
unique_books['tags'] = unique_books['tags'].apply(stem)

In [88]:
unique_books['tags'][0]

"harper lee the unforgett novel of a childhood in a sleepi southern town and the crisi of conscienc that rock it, to kill a mockingbird becam both an instant bestsel and a critic success when it wa first publish in 1960. it went on to win the pulitz prize in 1961 and wa later made into an academi award-win film, also a classic.compassionate, dramatic, and deepli moving, to kill a mockingbird take reader to the root of human behavior - to innoc and experience, kind and cruelty, love and hatred, humor and pathos. now with over 18 million copi in print and translat into forti languages, thi region stori by a young alabama woman claim univers appeal. harper lee alway consid her book to be a simpl love story. today it is regard as a masterpiec of american literature. 'classics' 'fiction' 'histor fiction' 'school' 'literature' 'young adult' 'historical' 'novels' 'read for school' 'high school' 'maycomb alabama (unit states)'"

In [89]:
unique_books['tags'] = unique_books['tags'].apply(lambda x:x.lower())

In [90]:
unique_books.head(10)

,title,tags,img
0,To Kill a Mockingbird,harper lee the unforgett novel of a childhood ...,http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"jane austen, anna quindlen (introduction) alte...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,stepheni meyer about three thing i wa absolut ...,http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"georg orwell, russel baker (preface), c.m. woo...",http://images.amazon.com/images/P/0451526341.0...
414,The Chronicles of Narnia,"c.s. lewis, paulin bayn (illustrator) journey ...",http://images.amazon.com/images/P/0590257889.0...
415,Gone with the Wind,"margaret mitchel scarlett o'hara, the beautifu...",http://images.amazon.com/images/P/0446365386.0...
458,The Hitchhiker's Guide to the Galaxy,dougla adam second befor the earth is demolish...,http://images.amazon.com/images/P/0671461494.0...
542,The Giving Tree,"shel silverstein ""onc there wa a tree...and sh...",http://images.amazon.com/images/P/0060256656.0...
563,Wuthering Heights,"emili brontë, richard j. dunn (editor), david ...",http://images.amazon.com/images/P/0553212583.0...
640,The Da Vinci Code,dan brown (goodread author) isbn 9780307277671...,http://images.amazon.com/images/P/0385504209.0...

In [91]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words='english')

In [92]:
vectors = cv.fit_transform(unique_books['tags']).toarray()

In [93]:
cv.get_feature_names_out()

array(['000', '10', '100', ..., 'zone', 'zoo', 'zu'], dtype=object)

In [94]:
from sklearn.metrics.pairwise import cosine_similarity

In [95]:
similarity = cosine_similarity(vectors)

In [96]:
def recommend(book):
    book_index = unique_books[unique_books['title'] == book].index[0]
    distances = similarity[book_index]
    book_list = sorted(list(enumerate(distances)),reverse=True,key=lambda x:x[1])[1:6]
    for i in book_list:
        print(unique_books.iloc[i[0]].title)

In [97]:
recommend('Twilight')

Gerald's Game
It
Carrie
Pet Sematary
The Long Walk

In [103]:
unique_books['title'].values

array(['To Kill a Mockingbird', 'Pride and Prejudice', 'Twilight', ...,
       'Vacuum Flowers', 'The Delta Star', 'Anasazi'], dtype=object)

In [104]:
pickle.dump(similarity,open('similarity.pkl','wb'))

In [105]:
unique_books.head(4)

,title,tags,img
0,To Kill a Mockingbird,harper lee the unforgett novel of a childhood ...,http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"jane austen, anna quindlen (introduction) alte...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,stepheni meyer about three thing i wa absolut ...,http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"georg orwell, russel baker (preface), c.m. woo...",http://images.amazon.com/images/P/0451526341.0...

In [106]:
rating_books.columns

Index(['bookId', 'title', 'series', 'author_x', 'rating_x', 'description',
       'language', 'isbn_x', 'genres', 'characters', 'bookFormat', 'edition',
       'pages', 'publisher_x', 'publishDate', 'firstPublishDate', 'awards',
       'numRatings', 'ratingsByStars', 'likedPercent', 'setting', 'coverImg',
       'bbeScore', 'bbeVotes', 'price', 'userid', 'isbn_y', 'rating_y',
       'author_y', 'year', 'publisher_y', 'Image-URL-S', 'img', 'Image-URL-L'],
      dtype='object')

In [107]:
pickle.dump(rating_books, open('rbook.pkl','wb'))

In [108]:
pickle.dump(model,open('model.pkl','wb'))

In [109]:
pickle.dump(book_pivot,open('book_pivot.pkl','wb'))

In [111]:
pickle.dump(unique_books,open('unibook.pkl','wb'))

In [113]:
unique_books.columns

Index(['title', 'tags', 'img'], dtype='object')

In [114]:
unique_books.head(10)

,title,tags,img
0,To Kill a Mockingbird,harper lee the unforgett novel of a childhood ...,http://images.amazon.com/images/P/0446310786.0...
186,Pride and Prejudice,"jane austen, anna quindlen (introduction) alte...",http://images.amazon.com/images/P/0451519167.0...
250,Twilight,stepheni meyer about three thing i wa absolut ...,http://images.amazon.com/images/P/0671644076.0...
274,Animal Farm,"georg orwell, russel baker (preface), c.m. woo...",http://images.amazon.com/images/P/0451526341.0...
414,The Chronicles of Narnia,"c.s. lewis, paulin bayn (illustrator) journey ...",http://images.amazon.com/images/P/0590257889.0...
415,Gone with the Wind,"margaret mitchel scarlett o'hara, the beautifu...",http://images.amazon.com/images/P/0446365386.0...
458,The Hitchhiker's Guide to the Galaxy,dougla adam second befor the earth is demolish...,http://images.amazon.com/images/P/0671461494.0...
542,The Giving Tree,"shel silverstein ""onc there wa a tree...and sh...",http://images.amazon.com/images/P/0060256656.0...
563,Wuthering Heights,"emili brontë, richard j. dunn (editor), david ...",http://images.amazon.com/images/P/0553212583.0...
640,The Da Vinci Code,dan brown (goodread author) isbn 9780307277671...,http://images.amazon.com/images/P/0385504209.0...